addSbtPlugin("org.typelevel"      % "sbt-tpolecat"        % "0.5.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"         % "0.6.4")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager" % "1.10.0")
addSbtPlugin("com.github.sbt"     % "sbt-release"         % "1.4.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"             % "0.4.7")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"     % "3.1.6")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"       % "2.0.12")
addSbtPlugin("org.scoverage"      % "sbt-coveralls"       % "1.3.12")
addDependencyTreePlugin
